### ISSUE TITLE
Broken starship connection

### ISSUE THREAD

**Issue by rdickert** [graphql/swapi-graphql#137] opened 2018-03-27 22:25 UTC
Looks like there's a regression: [This query](https://graphql.org/swapi-graphql/?query=%7B%0A%20%20person(id%3A%20%22cGVvcGxlOjE%3D%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%20%20%20%20starshipConnection%20%7B%0A%20%20%20%20%20%20starships%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) used to work but now returns error `No entry in local cache for [object Object]`

#b0a73b6 Seems to be ok, so it happened at some point since then

**Comment by rdickert** [comment] 2018-03-27 23:48
[This query](https://graphql.org/swapi-graphql/?query=%7B%0A%20%20person(id%3A%20%22cGVvcGxlOjE%3D%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20name%0A%09%09starshipConnection%20%7B%0A%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)is ok. It looks like some or all of the non-relay-spec fields are failing, but the edges/node path is ok. It's really useful to have the non-relay ones when first showing people graphql. I use these examples in training, which is why I noticed this!

**Comment by IvanGoncharov** [comment] 2018-03-28 12:25
@rdickert Thanks for reporting 👍 
I will try to fix it ASAP.

**Comment by IvanGoncharov** [comment] 2018-03-28 15:31
@rdickert Fixed in 29ec1bcc0ff626372b086a59c98d3bc3ab33bd55
Query from your initial post is working now.

I will keep this issue until I add new test cases to prevent similar regressions in future.

**Comment by rdickert** [comment] 2018-03-28 18:11
Awesome, thanks @IvanGoncharov

**Comment by GeneYoung1230** [comment] 2020-04-24 07:30
Hi, Excuse me. 
I run [this query](https://graphql.org/swapi-graphql?query=query%20%7B%0A%20%20person%20(personID%3A5)%7B%0A%20%20%20%20name%0A%20%20%20%20birthYear%0A%20%20%20%20created%0A%20%20%7D%0A%7D) which is written in the [book](http://shop.oreilly.com/product/0636920137269.do) example, but it return:
`{
  "errors": [
    {
      "message": "No entry in local cache for https://swapi.dev/api/people/5/",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "person"
      ]
    }
  ],
  "data": {
    "person": null
  }`

Is that normal?

**Comment by eaparnell** [comment] 2020-04-25 20:35
Or [this query](https://graphql.org/swapi-graphql?query=%7B%0A%20%20allPeople%20%7B%0A%20%20%20%20people%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A). It returns No entry in local cache for http://swapi.dev/api/people/?page=2. Seems like it should work.

**Comment by galactose** [comment] 2020-05-22 01:59
I came here with the same issue as @GeneYoung1230 with the issue in the [book](http://shop.oreilly.com/product/0636920137269.do).

**Comment by saheljalal** [comment] 2020-05-22 21:27
Yeah I'm seeing the same error for any query other than `{ allFilms }` unfortunately.

**Comment by tapayne88** [comment] 2020-05-24 18:41
I _think_ I have a fix for this (very crude fix) that works for me™️. Borrowed a lot from #175 which looked to be on the right track.

https://github.com/tapayne88/swapi-graphql/tree/local-cache-entry-fix

Make sure to remove the cache file if you have it and re-download it, something like this should do it
```shell
rm -f cache/data.json && yarn download
```

**Comment by mahmoudtokura** [comment] 2020-06-05 22:28
I am getting this error no matter the query I do. Please help.
```"No entry in local cache for http://swapi.dev/api/people/?page=2",```

**Closed** 2020-06-11 20:12 UTC
