### ISSUE TITLE
Facing some issue when I try to run npm start

### ISSUE THREAD

**Issue by KaustubhMemane** [graphql/swapi-graphql#125] opened 2017-11-11 10:24 UTC
npm install
added 666 packages in 86.589s

C:\swapi-graphql-master>npm start

> swapi-graphql@ start C:\swapi-graphql-master
> npm run download && babel-node src/server/main.js

> swapi-graphql@ download C:\swapi-graphql-master
> sh scripts/download

'sh' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swapi-graphql@ download: `sh scripts/download`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swapi-graphql@ download script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kmema\AppData\Roaming\npm-cache\_logs\2017-11-11T10_11_37_124Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swapi-graphql@ start: `npm run download && babel-node src/server/main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swapi-graphql@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kmema\AppData\Roaming\npm-cache\_logs\2017-11-11T10_11_37_279Z-debug.log

**Comment by IvanGoncharov** [comment] 2017-11-11 14:49
@KaustubhMemane Duplicate of #16 see this comment: https://github.com/graphql/swapi-graphql/issues/16#issuecomment-275256503

**Closed** 2017-11-13 02:35 UTC

**Comment by KaustubhMemane** [comment] 2017-11-13 02:37
@IvanGoncharov thank you, you solved my problem

**Comment by xgqfrms-gildata** [comment] 2018-03-16 04:38
# solution

```json
"scripts": {
    "download-shell-bug": "sh scripts/download",
    "download": "babel-node src/api/cachedData/downloadCache.js > src/api/cachedData/cache.js",
}
```

https://github.com/graphql/swapi-graphql/pull/131/commits/d13c1b0a36c73030a3d2639290f2dcace2d098fd
